create extension if not exists pgcrypto;
create type household_role as enum ('owner','manager','operator','reader');
create type journal_status as enum ('draft','posted','reversed');
create type sale_status as enum ('draft','confirmed','partially_paid','paid','overdue','cancelled');
create type entity_status as enum ('active','inactive','archived');

create table profiles(id uuid primary key references auth.users(id), display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table households(id uuid primary key default gen_random_uuid(), name text not null, base_currency text not null default 'USD', locale text not null default 'fr-CD', timezone text not null default 'Africa/Kinshasa', created_at timestamptz not null default now());
create table household_members(household_id uuid references households(id), user_id uuid references auth.users(id), role household_role not null, status text not null default 'active', invited_at timestamptz, joined_at timestamptz default now(), primary key(household_id,user_id));
create table invitations(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), email text not null, role household_role not null, status text not null default 'pending', created_at timestamptz not null default now());
create table audit_logs(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), actor_id uuid references auth.users(id), action text not null, entity text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create table activities(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), code text not null, name text not null, type text not null check(type in ('service','retail','venue','other')), active boolean not null default true, color text, display_order int not null default 0, unique(household_id,code));
create table categories(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), type text not null check(type in ('income','operating_expense','family_expense','other')), name text not null, parent_id uuid references categories(id), active boolean not null default true, unique(household_id,type,name));
create table contacts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), name text not null, is_customer boolean not null default false, is_supplier boolean not null default false, phone text, active boolean not null default true);
create table products(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), activity_id uuid not null references activities(id), type text not null, sku text, name text not null, suggested_price numeric(20,4), indicative_cost numeric(20,4), low_stock_threshold numeric(20,4) not null default 0, active boolean not null default true, unique(household_id,sku));
create table iptv_plans(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), name text not null, duration_days int not null, price numeric(20,4) not null, currency text not null, active boolean not null default true);
create table currencies(household_id uuid not null references households(id), code text not null, precision int not null default 2, active boolean not null default true, primary key(household_id,code));
create table exchange_rates(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), source_currency text not null, target_currency text not null, rate numeric(20,8) not null check(rate > 0), rate_date date not null, source text not null default 'manual', unique(household_id,source_currency,target_currency,rate_date));

create table ledger_accounts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), code text not null, name text not null, account_type text not null check(account_type in ('asset','liability','equity','income','cogs','operating_expense','family_expense')), parent_id uuid references ledger_accounts(id), system boolean not null default false, unique(household_id,code));
create table cash_accounts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), ledger_account_id uuid not null references ledger_accounts(id), name text not null, type text not null, currency text not null, active boolean not null default true);
create table document_sequences(household_id uuid not null references households(id), document_type text not null, year int not null, counter int not null default 0, primary key(household_id,document_type,year));
create table journal_entries(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), number text not null, type text not null, entry_date date not null, status journal_status not null default 'draft', description text, activity_id uuid references activities(id), idempotency_key text, reversal_of uuid references journal_entries(id), reversal_reason text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), posted_at timestamptz, unique(household_id,number), unique(household_id,idempotency_key));
create table journal_lines(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), journal_entry_id uuid not null references journal_entries(id), ledger_account_id uuid not null references ledger_accounts(id), debit_base numeric(20,4) not null default 0, credit_base numeric(20,4) not null default 0, currency text not null, source_amount numeric(20,4) not null, exchange_rate numeric(20,8) not null check(exchange_rate > 0), check(debit_base >= 0 and credit_base >= 0 and debit_base * credit_base = 0 and (debit_base + credit_base) > 0));
create table reconciliations(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), cash_account_id uuid not null references cash_accounts(id), period_start date not null, period_end date not null, statement_balance numeric(20,4) not null, difference numeric(20,4) not null, status text not null default 'draft');

create table sales(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), number text not null, activity_id uuid not null references activities(id), contact_id uuid references contacts(id), sale_date date not null, status sale_status not null default 'draft', currency text not null, total_source numeric(20,4) not null default 0, total_base numeric(20,4) not null default 0, due_date date, journal_entry_id uuid references journal_entries(id), unique(household_id,number));
create table sale_items(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), sale_id uuid not null references sales(id), product_id uuid references products(id), description text not null, quantity numeric(20,4) not null check(quantity > 0), unit_price numeric(20,4) not null, discount numeric(20,4) not null default 0, tax numeric(20,4) not null default 0, unit_cost numeric(20,4) not null default 0, total_source numeric(20,4) not null, total_base numeric(20,4) not null);
create table payments(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), sale_id uuid references sales(id), contact_id uuid references contacts(id), cash_account_id uuid not null references cash_accounts(id), amount_source numeric(20,4) not null, currency text not null, exchange_rate numeric(20,8) not null, payment_date date not null, status journal_status not null default 'draft', journal_entry_id uuid references journal_entries(id));
create table iptv_subscriptions(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), contact_id uuid references contacts(id), plan_id uuid references iptv_plans(id), customer_identifier text not null, activation_date date not null, expiration_date date not null, status text not null, sale_id uuid references sales(id));
create table billiard_sessions(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), started_at timestamptz, ended_at timestamptz, games_count numeric(20,4), duration_minutes int, rate numeric(20,4) not null, sale_id uuid references sales(id));

create table expenses(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), category_id uuid not null references categories(id), scope text not null check(scope in ('operating','family')), supplier_id uuid references contacts(id), cash_account_id uuid not null references cash_accounts(id), activity_id uuid references activities(id), expense_date date not null, amount_source numeric(20,4) not null, amount_base numeric(20,4) not null, currency text not null, status journal_status not null default 'draft', journal_entry_id uuid references journal_entries(id));
create table purchases(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), supplier_id uuid references contacts(id), cash_account_id uuid not null references cash_accounts(id), purchase_date date not null, currency text not null, fees_source numeric(20,4) not null default 0, total_source numeric(20,4) not null default 0, total_base numeric(20,4) not null default 0, status journal_status not null default 'draft', journal_entry_id uuid references journal_entries(id));
create table purchase_items(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), purchase_id uuid not null references purchases(id), product_id uuid not null references products(id), quantity numeric(20,4) not null check(quantity > 0), unit_cost numeric(20,4) not null, allocated_fees numeric(20,4) not null default 0, total_source numeric(20,4) not null);
create table recurring_templates(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), type text not null, frequency text not null, next_date date not null, payload jsonb not null);

create table inventory_locations(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), name text not null, primary_location boolean not null default false, active boolean not null default true);
create table stock_movements(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), product_id uuid not null references products(id), location_id uuid not null references inventory_locations(id), type text not null, quantity numeric(20,4) not null, unit_cost_base numeric(20,4) not null, reference_type text, reference_id uuid, movement_date date not null);
create table inventory_counts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), location_id uuid not null references inventory_locations(id), status text not null default 'draft', count_date date not null, responsible_id uuid references auth.users(id));
create table inventory_count_lines(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), inventory_count_id uuid not null references inventory_counts(id), product_id uuid not null references products(id), theoretical_quantity numeric(20,4) not null, counted_quantity numeric(20,4) not null, difference numeric(20,4) not null);

create table savings_goals(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), name text not null, target_amount numeric(20,4) not null, currency text not null, target_date date, priority int not null default 1, status entity_status not null default 'active');
create table savings_contributions(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), savings_goal_id uuid not null references savings_goals(id), source_cash_account_id uuid not null references cash_accounts(id), savings_cash_account_id uuid not null references cash_accounts(id), amount_source numeric(20,4) not null, contribution_date date not null, journal_entry_id uuid references journal_entries(id));
create table budgets(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), period_month date not null, scope text not null, currency text not null, unique(household_id,period_month,scope));
create table budget_lines(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), budget_id uuid not null references budgets(id), category_id uuid references categories(id), activity_id uuid references activities(id), amount numeric(20,4) not null, warn_threshold numeric(5,2) not null default 80, block_threshold numeric(5,2) not null default 100);
create table attachments(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), bucket_path text not null, mime_type text not null, size_bytes bigint not null, sha256 text not null, entity text not null, entity_id uuid not null, created_at timestamptz not null default now());

alter table profiles enable row level security; alter table households enable row level security; alter table household_members enable row level security; alter table invitations enable row level security; alter table audit_logs enable row level security; alter table activities enable row level security; alter table categories enable row level security; alter table contacts enable row level security; alter table products enable row level security; alter table iptv_plans enable row level security; alter table currencies enable row level security; alter table exchange_rates enable row level security; alter table ledger_accounts enable row level security; alter table cash_accounts enable row level security; alter table document_sequences enable row level security; alter table journal_entries enable row level security; alter table journal_lines enable row level security; alter table reconciliations enable row level security; alter table sales enable row level security; alter table sale_items enable row level security; alter table payments enable row level security; alter table iptv_subscriptions enable row level security; alter table billiard_sessions enable row level security; alter table expenses enable row level security; alter table purchases enable row level security; alter table purchase_items enable row level security; alter table recurring_templates enable row level security; alter table inventory_locations enable row level security; alter table stock_movements enable row level security; alter table inventory_counts enable row level security; alter table inventory_count_lines enable row level security; alter table savings_goals enable row level security; alter table savings_contributions enable row level security; alter table budgets enable row level security; alter table budget_lines enable row level security; alter table attachments enable row level security;

create function is_household_member(h uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_members m where m.household_id=h and m.user_id=auth.uid() and m.status='active') $$;
create function household_role(h uuid) returns household_role language sql stable security definer set search_path=public as $$ select role from household_members m where m.household_id=h and m.user_id=auth.uid() and m.status='active' limit 1 $$;
create function can_write_household(h uuid) returns boolean language sql stable security definer set search_path=public as $$ select household_role(h) in ('owner','manager','operator') $$;

create policy profile_self on profiles using (id=auth.uid()) with check (id=auth.uid());
create policy household_select on households for select using (is_household_member(id));
create policy member_select on household_members for select using (is_household_member(household_id));

-- generated policies for all household-owned tables
create policy invitations_read on invitations for select using (is_household_member(household_id)); create policy invitations_write on invitations for all using (household_role(household_id) in ('owner','manager')) with check (household_role(household_id) in ('owner','manager'));
create policy audit_read on audit_logs for select using (household_role(household_id)='owner');

create function install_household_policy(t regclass) returns void language plpgsql as $$ begin execute format('create policy %I_select on %s for select using (is_household_member(household_id))', t::text||'_member', t); execute format('create policy %I_write on %s for all using (can_write_household(household_id)) with check (can_write_household(household_id))', t::text||'_writer', t); end $$;
select install_household_policy(x) from unnest(array['activities','categories','contacts','products','iptv_plans','currencies','exchange_rates','ledger_accounts','cash_accounts','document_sequences','journal_entries','journal_lines','reconciliations','sales','sale_items','payments','iptv_subscriptions','billiard_sessions','expenses','purchases','purchase_items','recurring_templates','inventory_locations','stock_movements','inventory_counts','inventory_count_lines','savings_goals','savings_contributions','budgets','budget_lines','attachments']::regclass[]) x;
drop function install_household_policy(regclass);

create function prevent_posted_line_changes() returns trigger language plpgsql as $$ begin if exists(select 1 from journal_entries e where e.id=coalesce(old.journal_entry_id,new.journal_entry_id) and e.status in ('posted','reversed')) then raise exception 'posted journal lines are immutable'; end if; return coalesce(new,old); end $$;
create trigger journal_lines_no_change before update or delete on journal_lines for each row execute function prevent_posted_line_changes();
create function assert_entry_can_post(p_entry uuid) returns void language plpgsql as $$ declare line_count int; debit numeric(20,4); credit numeric(20,4); begin select count(*),coalesce(sum(debit_base),0),coalesce(sum(credit_base),0) into line_count,debit,credit from journal_lines where journal_entry_id=p_entry; if line_count < 2 or debit <> credit then raise exception 'posted journal entry must have at least two balanced lines'; end if; end $$;
create function post_journal_entry(p_entry uuid, p_idempotency_key text) returns uuid language plpgsql security definer set search_path=public as $$ declare h uuid; begin select household_id into h from journal_entries where id=p_entry; if not can_write_household(h) then raise exception 'not allowed'; end if; perform assert_entry_can_post(p_entry); update journal_entries set status='posted', posted_at=now(), idempotency_key=coalesce(idempotency_key,p_idempotency_key) where id=p_entry and status='draft'; return p_entry; end $$;
create function reverse_journal_entry(p_entry uuid, p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare original journal_entries%rowtype; new_id uuid := gen_random_uuid(); begin if nullif(trim(p_reason),'') is null then raise exception 'reversal reason required'; end if; select * into original from journal_entries where id=p_entry and status='posted'; if not found or not can_write_household(original.household_id) then raise exception 'not allowed'; end if; insert into journal_entries(id,household_id,number,type,entry_date,status,description,reversal_of,reversal_reason,created_by,posted_at) values(new_id,original.household_id,original.number||'-REV','reversal',current_date,'posted','Annulation: '||p_reason,original.id,p_reason,auth.uid(),now()); insert into journal_lines(household_id,journal_entry_id,ledger_account_id,debit_base,credit_base,currency,source_amount,exchange_rate) select household_id,new_id,ledger_account_id,credit_base,debit_base,currency,source_amount,exchange_rate from journal_lines where journal_entry_id=original.id; update journal_entries set status='reversed' where id=original.id; return new_id; end $$;

create function bootstrap_household(p_household_name text, p_display_name text) returns uuid language plpgsql security definer set search_path=public as $$ declare uid uuid := auth.uid(); h uuid := gen_random_uuid(); cash_usd uuid; cash_cdf uuid; mpesa_usd uuid; mpesa_cdf uuid; bank uuid; savings uuid; begin if uid is null then raise exception 'authentication required'; end if; if exists(select 1 from household_members where user_id=uid and status='active') then raise exception 'user already belongs to a household'; end if; insert into profiles(id,display_name) values(uid,p_display_name) on conflict(id) do update set display_name=excluded.display_name; insert into households(id,name) values(h,p_household_name); insert into household_members(household_id,user_id,role,status,joined_at) values(h,uid,'owner','active',now()); insert into currencies(household_id,code,precision) values(h,'USD',2),(h,'CDF',0); insert into activities(household_id,code,name,type,active,display_order) values(h,'IPTV','Vente IPTV','service',true,1),(h,'MINI_UPS','Vente Mini UPS','retail',true,2),(h,'ANDROID_TV_BOX','Vente Android TV Box','retail',true,3),(h,'BILLIARD','Table de billard','venue',false,4); insert into categories(household_id,type,name) values(h,'operating_expense','Achat marchandises'),(h,'operating_expense','Frais mobile money'),(h,'family_expense','Nourriture'),(h,'family_expense','Transport'),(h,'income','Autre entrée'); insert into ledger_accounts(household_id,code,name,account_type,system) values(h,'cash','Trésorerie','asset',true),(h,'inventory','Stock','asset',true),(h,'receivable','Créances clients','asset',true),(h,'savings','Épargne','asset',true),(h,'sales','Ventes','income',true),(h,'cogs','Coût des ventes','cogs',true),(h,'opex','Dépenses exploitation','operating_expense',true),(h,'family','Dépenses familiales','family_expense',true),(h,'equity','Capital familial','equity',true); select id into cash_usd from ledger_accounts where household_id=h and code='cash'; select id into savings from ledger_accounts where household_id=h and code='savings'; insert into cash_accounts(household_id,ledger_account_id,name,type,currency) values(h,cash_usd,'Caisse USD','cash','USD'),(h,cash_usd,'Caisse CDF','cash','CDF'),(h,cash_usd,'M-Pesa USD','mobile_money','USD'),(h,cash_usd,'M-Pesa CDF','mobile_money','CDF'),(h,cash_usd,'Banque','bank','USD'),(h,savings,'Épargne','savings','USD'); insert into inventory_locations(household_id,name,primary_location) values(h,'Principal',true); insert into audit_logs(household_id,actor_id,action,entity,entity_id) values(h,uid,'bootstrap','household',h); return h; end $$;

create function get_dashboard_kpis(p_household_id uuid) returns table(revenue numeric,gross_profit numeric,net_profit numeric,family_expenses numeric,savings numeric,cash numeric) language sql stable security definer set search_path=public as $$ select coalesce(sum(case when a.account_type='income' then l.credit_base-l.debit_base else 0 end),0), coalesce(sum(case when a.account_type='income' then l.credit_base-l.debit_base when a.account_type='cogs' then l.credit_base-l.debit_base else 0 end),0), coalesce(sum(case when a.account_type in ('income','cogs','operating_expense') then l.credit_base-l.debit_base else 0 end),0), coalesce(sum(case when a.account_type='family_expense' then l.debit_base-l.credit_base else 0 end),0), coalesce(sum(case when a.code='savings' then l.debit_base-l.credit_base else 0 end),0), coalesce(sum(case when a.account_type='asset' then l.debit_base-l.credit_base else 0 end),0) from journal_lines l join journal_entries e on e.id=l.journal_entry_id join ledger_accounts a on a.id=l.ledger_account_id where l.household_id=p_household_id and is_household_member(p_household_id) and e.status='posted' $$;

revoke all on function bootstrap_household(text,text) from public; grant execute on function bootstrap_household(text,text) to authenticated;
revoke all on function post_journal_entry(uuid,text) from public; grant execute on function post_journal_entry(uuid,text) to authenticated;
revoke all on function reverse_journal_entry(uuid,text) from public; grant execute on function reverse_journal_entry(uuid,text) to authenticated;
revoke all on function get_dashboard_kpis(uuid) from public; grant execute on function get_dashboard_kpis(uuid) to authenticated;
