create extension if not exists pgcrypto;
create type household_role as enum ('owner','manager','operator','reader');
create type journal_status as enum ('draft','posted','reversed');
create table households(id uuid primary key default gen_random_uuid(), name text not null, base_currency text not null default 'USD', locale text not null default 'fr-CD', timezone text not null default 'Africa/Kinshasa', created_at timestamptz not null default now());
create table profiles(id uuid primary key, display_name text, created_at timestamptz not null default now());
create table household_members(household_id uuid references households(id), user_id uuid not null, role household_role not null, status text not null default 'active', primary key(household_id,user_id));
create table activities(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), code text not null, name text not null, type text not null, active boolean not null default true, display_order int not null default 0, unique(household_id,code));
create table ledger_accounts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), code text not null, name text not null, account_type text not null, unique(household_id,code));
create table cash_accounts(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), ledger_account_id uuid not null references ledger_accounts(id), name text not null, type text not null, currency text not null, active boolean not null default true);
create table journal_entries(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), number text not null, type text not null, entry_date date not null, status journal_status not null default 'draft', description text, idempotency_key text, reversal_of uuid references journal_entries(id), created_at timestamptz not null default now(), unique(household_id,number), unique(household_id,idempotency_key));
create table journal_lines(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), journal_entry_id uuid not null references journal_entries(id), ledger_account_id uuid not null references ledger_accounts(id), debit_base numeric(20,4) not null default 0, credit_base numeric(20,4) not null default 0, currency text not null, source_amount numeric(20,4) not null, exchange_rate numeric(20,8) not null, check(debit_base >= 0 and credit_base >= 0 and debit_base * credit_base = 0));
create table audit_logs(id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id), actor_id uuid, action text not null, entity text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
alter table households enable row level security; alter table household_members enable row level security; alter table activities enable row level security; alter table ledger_accounts enable row level security; alter table cash_accounts enable row level security; alter table journal_entries enable row level security; alter table journal_lines enable row level security; alter table audit_logs enable row level security;
create function is_household_member(h uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_members m where m.household_id=h and m.user_id=auth.uid() and m.status='active') $$;
create policy household_isolation on households using (is_household_member(id));
create policy member_isolation on household_members using (is_household_member(household_id));
create policy activity_isolation on activities using (is_household_member(household_id));
create policy ledger_isolation on ledger_accounts using (is_household_member(household_id));
create policy cash_isolation on cash_accounts using (is_household_member(household_id));
create policy entry_isolation on journal_entries using (is_household_member(household_id));
create policy line_isolation on journal_lines using (is_household_member(household_id));
create policy audit_isolation on audit_logs using (is_household_member(household_id));
create function assert_posted_entry_balanced() returns trigger language plpgsql as $$ begin if new.status='posted' and exists(select 1 from journal_lines where journal_entry_id=new.id having coalesce(sum(debit_base),0) <> coalesce(sum(credit_base),0)) then raise exception 'posted journal entry must be balanced'; end if; return new; end $$;
create trigger journal_entries_balance before update of status on journal_entries for each row execute function assert_posted_entry_balanced();
